baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://resume.tworitdash.in/" # the base hostname & protocol for your site
markdown: kramdown
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
